// Library
import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";

// Components
import AntdProvider from "@/components/wrapper/AntdProvider";
import QueryProviderWrapper from "@/components/wrapper/QueryProviderWrapper";
import RecoilRootWrapper from "@/components/wrapper/RecoilRootWrapper";

const pretendard = localFont({
    src: [
        {
            path: "../public/fonts/Pretendard-ExtraLight.woff2",
            weight: "200",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-Light.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-SemiBold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../public/fonts/Pretendard-ExtraBold.woff2",
            weight: "800",
            style: "normal",
        },
    ],
    variable: "--font-pretendard",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${pretendard.variable} font-pretendard`}>
                <Script src="https://cdn.iamport.kr/v1/iamport.js" />

                <Script src="https://cdn.iamport.kr/v1/iamport.js" strategy="beforeInteractive" />
                <AntdProvider>
                    <RecoilRootWrapper>
                        <QueryProviderWrapper>{children}</QueryProviderWrapper>
                    </RecoilRootWrapper>
                </AntdProvider>
            </body>
        </html>
    );
}
